/* CREATING THE SEQUENCES */ 
CREATE SEQUENCE EMPLOYEE_SEQUENCE
START WITH 1
INCREMENT BY 1
MAXVALUE 100
; 
CREATE SEQUENCE MANAGER_SEQUENCE
START WITH 1
INCREMENT BY 1
MAXVALUE 100
;

CREATE SEQUENCE REQUEST_SEQUENCE
START WITH 1
INCREMENT BY 1
MAXVALUE 100
; 
CREATE SEQUENCE REIMBURSEMENT_SEQUENCE
START WITH 1
INCREMENT BY 1
MAXVALUE 100
;

/* CREATING TABLES 
EMPLOYEE TABLE */
CREATE TABLE EMPLOYEE1 (
EMPLOYEE_FN VARCHAR2(100),
EMPLOYEE_LN VARCHAR2(100),
EMPLOYEE_EM VARCHAR2(200),
EMPLOYEE_RR VARCHAR2(100)
);

/*MANAGER TABLE */
CREATE TABLE MANAGER (
MANAGER_FN VARCHAR2(100),
MANAGER_LN VARCHAR2(100),
MANAGER_EM VARCHAR2(200),
MANAGER_RR VARCHAR2(100)
);

/*REQUEST TABLE */
CREATE TABLE REQUEST (
REIMBURSMENTS INT,
EMPLOYEE_ID INT,
EMPLOYEE_FN VARCHAR2(100),
EMPLOYEE_EM VARCHAR2(200)
); 

/*REIMBURSEMENT TABLE */
CREATE TABLE REIMBURSEMENT (
REIMBURSEMENTS VARCHAR2(50),
REQUEST_NUM INT
);

/*ALTERING COLUMN IN REQUEST TABLE */
ALTER TABLE REQUEST RENAME COLUMN
REIMBURSMENTS TO REIMBURSEMENTS_ID;  

/* ALTERING TABLES TO ADD IDs */
ALTER TABLE EMPLOYEE1 ADD(
EMPLOYEE_ID INT
);

ALTER TABLE MANAGER ADD(
MANAGER_ID INT
);

ALTER TABLE REIMBURSEMENT ADD(
REIMBURSEMENTS_ID INT
);

ALTER TABLE REQUEST ADD(
REQUEST_ID INT
);

/*INSERTING INFORMATION EMPLOYEE1 TABLE */
INSERT INTO EMPLOYEE1 VALUES('PATRICK', 'SPENCE', '@GMAIL', 'HOTEL', 1);
INSERT INTO EMPLOYEE1 VALUES('JESSIE', 'GONZALES', '@HOTMAIL', 'GAS', 2);
INSERT INTO EMPLOYEE1 VALUES('JESSIE', 'CONZALES', '@HOTMAIL', 'HOTEL', 2);
INSERT INTO EMPLOYEE1 VALUES('GABRIEL', 'SAINTVIL', '@GMAIL', 'HOTEL', 3);
INSERT INTO EMPLOYEE1 VALUES('GISELLE', 'JONES', '@YAHOO', 'HOTEL', 4);
INSERT INTO EMPLOYEE1 VALUES('GISELLE', 'JONES', '@YAHOO', 'GAS', 4);
INSERT INTO EMPLOYEE1 VALUES('GISELLE', 'JONES', '@YAHOO', 'FOOD', 4);
INSERT INTO EMPLOYEE1 VALUES('JEAN-PIERRE', 'NAKAMA', '@GMAIL', 'HOTEL', 5);

/*CREATING MANAGEMENT TABLE AND SEQUENCE */
CREATE SEQUENCE MANAGEMENT_SEQUENCE
START WITH 1
INCREMENT BY 1
MAXVALUE 100
/
CREATE TABLE MANAGEMENT (
MANAGER_ID INT,
EMPLOYEE1_ID INT,
REQUEST_ID INT
);

/*INSERTING INTO MANAGEMENT TABLE */
INSERT INTO MANAGEMENT VALUES( 30, 1, 1);
INSERT INTO MANAGEMENT VALUES( 30, 2, 2);
INSERT INTO MANAGEMENT VALUES( 30, 2, 3);
INSERT INTO MANAGEMENT VALUES( 10, 3, 4);
INSERT INTO MANAGEMENT VALUES( 10, 5, 8);
INSERT INTO MANAGEMENT VALUES( 20, 4, 7);

/*UPDATING EMPLOYEE1 TABLE */ 

ALTER TABLE EMPLOYEE1 ADD(
MANAGER_ID INT
);

UPDATE EMPLOYEE1 SET MANAGER_ID= 20 WHERE EMPLOYEE_ID=4; 

/*INSERTING INTO THE REQUEST TABLE */
INSERT INTO REQUEST VALUES( 1, 1, 'PATRICK', '@GMAIL', 1);
INSERT INTO REQUEST VALUES( 1, 2, 'JESSIE', '@HOTMAIL', 2);
INSERT INTO REQUEST VALUES( 2, 2, 'JESSIE', '@HOTMAIL', 3);
INSERT INTO REQUEST VALUES( 1, 3, 'GABRIEL', '@GMAIL', 4);
INSERT INTO REQUEST VALUES( 1, 4, 'GISELLE', '@YAHOO', 5);
INSERT INTO REQUEST VALUES( 2, 4, 'GISELLE', '@YAHOO', 6);
INSERT INTO REQUEST VALUES( 3, 4, 'GISELLE', '@YAHOO', 7);
INSERT INTO REQUEST VALUES( 1, 5, 'JEAN-PIERRE', '@GMAIL', 8);
INSERT INTO REQUEST VALUES( 2, 10, 'MIGUEL', '@HOTMAIL', 9);
INSERT INTO REQUEST VALUES( 3, 10, 'MIGUEL', '@HOTMAIL', 10);
INSERT INTO REQUEST VALUES( 1, 20, 'LAUREN', '@MSN', 11);
INSERT INTO REQUEST VALUES( 3, 20, 'LARUEN', '@MSN', 12);
INSERT INTO REQUEST VALUES( 3, 30, 'NATASHA', '@GMAIL', 13);

/*INSERTING INTO THE REIMBURSEMENT TABLE */
INSERT INTO REIMBURSEMENT VALUES( 'HOTEL', 6, 1);
INSERT INTO REIMBURSEMENT VALUES( 'GAS', 3, 2);
INSERT INTO REIMBURSEMENT VALUES( 'FOOD', 4, 3); 

/*STORED PROCEDURE TO REQUEST ALL DATA FROM REQUEST TABLE */
CREATE OR REPLACE PROCEDURE spSELECTALLREQUEST 
AS
BEGIN
SELECT * FROM REQUEST;
END;
/

EXEC spSELECTALLREQUEST; 

/*STORED PROCEDURES TO REQUEST REIMBURSEMENTS BY ID */ 
CREATE OR REPLACE PROCEDURE spSELECTALLREQUEST  @REIMBURSEMENT_ID INT 
AS
SELECT * FROM REQUEST WHERE @REIMBURSEMENT_ID=1
COMMIT;
END; 
/

EXEC spSELECTALLREQUEST @REIMBURSEMENT_ID=1; 

CREATE OR REPLACE PROCEDURE spSELECTALLREQUEST @REIMBURSEMENT_ID INT 
AS
SELECT * FROM REQUEST WHERE @REIMBURSEMENT_ID=2
COMMIT;
END;
/

EXEC spSELECTALLREQUEST @REIMBURSEMENT_ID=2; 

CREATE OR REPLACE PROCEDURE spSELECTALLREQUEST @REIMBURSEMENT_ID INT 
AS
SELECT * FROM REQUEST WHERE @REIMBURSEMENT_ID=3
COMMIT;
END;
/

EXEC spSELECTALLREQUEST @REIMBURSEMENT_ID=3;