CREATE SEQUENCE EMPLOYEE2_SEQUENCE
START WITH 1000
INCREMENT BY 1;
/
CREATE TABLE EMPLOYEE2_
(
    EMPLOYEE_ID INT PRIMARY KEY,
    EMP_FIRSTNAME VARCHAR2(100),
    EMP_LASTNAME VARCHAR2(100),
    DEPARTMENT_ID INT,
    SALARY FLOAT,
    EMP_EMAIL VARCHAR2(100)
)
CREATE SEQUENCE DEPARTMENT_SEQUENCE
START WITH 1000
INCREMENT BY 1;
/
CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100)
    
)